
KerasJson: storedANN/sine_v0.1.json
KerasH5: storedANN/sine_v0.1_weights.h5
OutputDir: sinetest
ProjectName: sinetest
# BASYS3
#XilinxPart: xc7a35tcpg236-1
# NEXYS 4
XilinxPart: xc7a100tcsg324-1
ClockPeriod: 10ns

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
        Model:
                Precision: ap_fixed<16,6>
                ReuseFactor: 20
                Strategy: Latency  # options: Latency/Resource

